apiVersion: v1
kind: Pod
metadata:
  name: shop-app-pod
  labels:
    environment: test
    app: shop-app
spec:
  containers:
    - name: shop-app
      image: ghcr.io/devops_cicd_final/shop_app:latest
  imagePullSecrets:
    - name: regcred