apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb-sts
spec:
  serviceName: "mysqldb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8
          ports:
            - containerPort: 3306
              name: mysqldb-port
          envFrom:
            - secretRef:
                name: mysqldb-secrets
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_USER
              value: username
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql/
            - name: mysqldb-config-map
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysqldb-config-map
          configMap:
            name: mysqldb-configmap

  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300M
