apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-configmap
data:
  0000-create-table.sql: |
    CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30),
    price INT
    );
  0001-insert-data.sql: |
    INSERT INTO products (name, price)
    VALUES ("Hammer", 199),
      ("Nail", 99),
      ("Screwdriver", 79);
  0002-create-user.sql: |
    CREATE TABLE user (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(100) UNIQUE NOT NULL,
      password VARCHAR(200) NOT NULL
    );
